spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:beerapidb;DB_CLOSE_ON_EXIT=FALSE
    username: user
    password: pass
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
server:
  error:
    include-message: always